/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ITokenRouteImport } from './routes/i.$token'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'
import { Route as AuthGoogleStartRouteImport } from './routes/auth.google.start'
import { Route as ITokenCoachAvatarRouteImport } from './routes/i.$token_.coach-avatar'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ITokenRoute = ITokenRouteImport.update({
  id: '/i/$token',
  path: '/i/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleStartRoute = AuthGoogleStartRouteImport.update({
  id: '/auth/google/start',
  path: '/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ITokenCoachAvatarRoute = ITokenCoachAvatarRouteImport.update({
  id: '/i/$token_/coach-avatar',
  path: '/i/$token/coach-avatar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/health': typeof HealthRoute
  '/i/$token': typeof ITokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/i/$token/coach-avatar': typeof ITokenCoachAvatarRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/i/$token': typeof ITokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/i/$token/coach-avatar': typeof ITokenCoachAvatarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/health': typeof HealthRoute
  '/i/$token': typeof ITokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/start': typeof AuthGoogleStartRoute
  '/i/$token_/coach-avatar': typeof ITokenCoachAvatarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/health'
    | '/i/$token'
    | '/legal/privacy'
    | '/legal/terms'
    | '/auth/google/callback'
    | '/auth/google/start'
    | '/i/$token/coach-avatar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/i/$token'
    | '/legal/privacy'
    | '/legal/terms'
    | '/auth/google/callback'
    | '/auth/google/start'
    | '/i/$token/coach-avatar'
  id:
    | '__root__'
    | '/health'
    | '/i/$token'
    | '/legal/privacy'
    | '/legal/terms'
    | '/auth/google/callback'
    | '/auth/google/start'
    | '/i/$token_/coach-avatar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HealthRoute: typeof HealthRoute
  ITokenRoute: typeof ITokenRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthGoogleStartRoute: typeof AuthGoogleStartRoute
  ITokenCoachAvatarRoute: typeof ITokenCoachAvatarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$token': {
      id: '/i/$token'
      path: '/i/$token'
      fullPath: '/i/$token'
      preLoaderRoute: typeof ITokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/start': {
      id: '/auth/google/start'
      path: '/auth/google/start'
      fullPath: '/auth/google/start'
      preLoaderRoute: typeof AuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$token_/coach-avatar': {
      id: '/i/$token_/coach-avatar'
      path: '/i/$token/coach-avatar'
      fullPath: '/i/$token/coach-avatar'
      preLoaderRoute: typeof ITokenCoachAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HealthRoute: HealthRoute,
  ITokenRoute: ITokenRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthGoogleStartRoute: AuthGoogleStartRoute,
  ITokenCoachAvatarRoute: ITokenCoachAvatarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
