/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as RoomRouteImport } from './routes/room'
import { Route as CoachBotRouteImport } from './routes/coach.bot'
import { Route as CoachMiniappRouteImport } from './routes/coach.miniapp'
import { Route as EmailInviteRouteImport } from './routes/email.invite'
import { Route as EmailReminderRouteImport } from './routes/email.reminder'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as JoinTokenRouteImport } from './routes/join.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachBotRoute = CoachBotRouteImport.update({
  id: '/coach/bot',
  path: '/coach/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachMiniappRoute = CoachMiniappRouteImport.update({
  id: '/coach/miniapp',
  path: '/coach/miniapp',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailInviteRoute = EmailInviteRouteImport.update({
  id: '/email/invite',
  path: '/email/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailReminderRoute = EmailReminderRouteImport.update({
  id: '/email/reminder',
  path: '/email/reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/facts': typeof FactsRoute
  '/room': typeof RoomRoute
  '/coach/bot': typeof CoachBotRoute
  '/coach/miniapp': typeof CoachMiniappRoute
  '/email/invite': typeof EmailInviteRoute
  '/email/reminder': typeof EmailReminderRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/facts': typeof FactsRoute
  '/room': typeof RoomRoute
  '/coach/bot': typeof CoachBotRoute
  '/coach/miniapp': typeof CoachMiniappRoute
  '/email/invite': typeof EmailInviteRoute
  '/email/reminder': typeof EmailReminderRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/facts': typeof FactsRoute
  '/room': typeof RoomRoute
  '/coach/bot': typeof CoachBotRoute
  '/coach/miniapp': typeof CoachMiniappRoute
  '/email/invite': typeof EmailInviteRoute
  '/email/reminder': typeof EmailReminderRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/facts'
    | '/room'
    | '/coach/bot'
    | '/coach/miniapp'
    | '/email/invite'
    | '/email/reminder'
    | '/invite/$token'
    | '/join/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/facts'
    | '/room'
    | '/coach/bot'
    | '/coach/miniapp'
    | '/email/invite'
    | '/email/reminder'
    | '/invite/$token'
    | '/join/$token'
  id:
    | '__root__'
    | '/'
    | '/facts'
    | '/room'
    | '/coach/bot'
    | '/coach/miniapp'
    | '/email/invite'
    | '/email/reminder'
    | '/invite/$token'
    | '/join/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FactsRoute: typeof FactsRoute
  RoomRoute: typeof RoomRoute
  CoachBotRoute: typeof CoachBotRoute
  CoachMiniappRoute: typeof CoachMiniappRoute
  EmailInviteRoute: typeof EmailInviteRoute
  EmailReminderRoute: typeof EmailReminderRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts': {
      id: '/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/bot': {
      id: '/coach/bot'
      path: '/coach/bot'
      fullPath: '/coach/bot'
      preLoaderRoute: typeof CoachBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/miniapp': {
      id: '/coach/miniapp'
      path: '/coach/miniapp'
      fullPath: '/coach/miniapp'
      preLoaderRoute: typeof CoachMiniappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/invite': {
      id: '/email/invite'
      path: '/email/invite'
      fullPath: '/email/invite'
      preLoaderRoute: typeof EmailInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/reminder': {
      id: '/email/reminder'
      path: '/email/reminder'
      fullPath: '/email/reminder'
      preLoaderRoute: typeof EmailReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FactsRoute: FactsRoute,
  RoomRoute: RoomRoute,
  CoachBotRoute: CoachBotRoute,
  CoachMiniappRoute: CoachMiniappRoute,
  EmailInviteRoute: EmailInviteRoute,
  EmailReminderRoute: EmailReminderRoute,
  InviteTokenRoute: InviteTokenRoute,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
