/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as MainMiniAppRouteImport } from './routes/main-mini-app'
import { Route as AvailabilityIndexRouteImport } from './routes/availability/index'
import { Route as AvailabilityHoursRouteImport } from './routes/availability/hours'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as ClientsNewRouteImport } from './routes/clients/new'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as SessionsNewRouteImport } from './routes/sessions/new'
import { Route as AvailabilityHoursDaysRouteImport } from './routes/availability/hours_.days'
import { Route as ClientsClientIdAvatarRouteImport } from './routes/clients/$clientId_.avatar'
import { Route as SessionsSessionIdRescheduleRouteImport } from './routes/sessions/$sessionId_.reschedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const MainMiniAppRoute = MainMiniAppRouteImport.update({
  id: '/main-mini-app',
  path: '/main-mini-app',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityIndexRoute = AvailabilityIndexRouteImport.update({
  id: '/availability/',
  path: '/availability/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityHoursRoute = AvailabilityHoursRouteImport.update({
  id: '/availability/hours',
  path: '/availability/hours',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityHoursDaysRoute = AvailabilityHoursDaysRouteImport.update({
  id: '/availability/hours_/days',
  path: '/availability/hours/days',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdAvatarRoute = ClientsClientIdAvatarRouteImport.update({
  id: '/clients/$clientId_/avatar',
  path: '/clients/$clientId/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRescheduleRoute =
  SessionsSessionIdRescheduleRouteImport.update({
    id: '/sessions/$sessionId_/reschedule',
    path: '/sessions/$sessionId/reschedule',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/main-mini-app': typeof MainMiniAppRoute
  '/availability/hours': typeof AvailabilityHoursRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/availability/': typeof AvailabilityIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/availability/hours/days': typeof AvailabilityHoursDaysRoute
  '/clients/$clientId/avatar': typeof ClientsClientIdAvatarRoute
  '/sessions/$sessionId/reschedule': typeof SessionsSessionIdRescheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/main-mini-app': typeof MainMiniAppRoute
  '/availability/hours': typeof AvailabilityHoursRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/availability': typeof AvailabilityIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/availability/hours/days': typeof AvailabilityHoursDaysRoute
  '/clients/$clientId/avatar': typeof ClientsClientIdAvatarRoute
  '/sessions/$sessionId/reschedule': typeof SessionsSessionIdRescheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/main-mini-app': typeof MainMiniAppRoute
  '/availability/hours': typeof AvailabilityHoursRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/availability/': typeof AvailabilityIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/availability/hours_/days': typeof AvailabilityHoursDaysRoute
  '/clients/$clientId_/avatar': typeof ClientsClientIdAvatarRoute
  '/sessions/$sessionId_/reschedule': typeof SessionsSessionIdRescheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/main-mini-app'
    | '/availability/hours'
    | '/clients/$clientId'
    | '/clients/new'
    | '/legal/privacy'
    | '/legal/terms'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/availability/'
    | '/clients/'
    | '/sessions/'
    | '/availability/hours/days'
    | '/clients/$clientId/avatar'
    | '/sessions/$sessionId/reschedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/main-mini-app'
    | '/availability/hours'
    | '/clients/$clientId'
    | '/clients/new'
    | '/legal/privacy'
    | '/legal/terms'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/availability'
    | '/clients'
    | '/sessions'
    | '/availability/hours/days'
    | '/clients/$clientId/avatar'
    | '/sessions/$sessionId/reschedule'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/main-mini-app'
    | '/availability/hours'
    | '/clients/$clientId'
    | '/clients/new'
    | '/legal/privacy'
    | '/legal/terms'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/availability/'
    | '/clients/'
    | '/sessions/'
    | '/availability/hours_/days'
    | '/clients/$clientId_/avatar'
    | '/sessions/$sessionId_/reschedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  MainMiniAppRoute: typeof MainMiniAppRoute
  AvailabilityHoursRoute: typeof AvailabilityHoursRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsNewRoute: typeof SessionsNewRoute
  AvailabilityIndexRoute: typeof AvailabilityIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  AvailabilityHoursDaysRoute: typeof AvailabilityHoursDaysRoute
  ClientsClientIdAvatarRoute: typeof ClientsClientIdAvatarRoute
  SessionsSessionIdRescheduleRoute: typeof SessionsSessionIdRescheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main-mini-app': {
      id: '/main-mini-app'
      path: '/main-mini-app'
      fullPath: '/main-mini-app'
      preLoaderRoute: typeof MainMiniAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability/': {
      id: '/availability/'
      path: '/availability'
      fullPath: '/availability/'
      preLoaderRoute: typeof AvailabilityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability/hours': {
      id: '/availability/hours'
      path: '/availability/hours'
      fullPath: '/availability/hours'
      preLoaderRoute: typeof AvailabilityHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability/hours_/days': {
      id: '/availability/hours_/days'
      path: '/availability/hours/days'
      fullPath: '/availability/hours/days'
      preLoaderRoute: typeof AvailabilityHoursDaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId_/avatar': {
      id: '/clients/$clientId_/avatar'
      path: '/clients/$clientId/avatar'
      fullPath: '/clients/$clientId/avatar'
      preLoaderRoute: typeof ClientsClientIdAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId_/reschedule': {
      id: '/sessions/$sessionId_/reschedule'
      path: '/sessions/$sessionId/reschedule'
      fullPath: '/sessions/$sessionId/reschedule'
      preLoaderRoute: typeof SessionsSessionIdRescheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  MainMiniAppRoute: MainMiniAppRoute,
  AvailabilityHoursRoute: AvailabilityHoursRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsNewRoute: SessionsNewRoute,
  AvailabilityIndexRoute: AvailabilityIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  AvailabilityHoursDaysRoute: AvailabilityHoursDaysRoute,
  ClientsClientIdAvatarRoute: ClientsClientIdAvatarRoute,
  SessionsSessionIdRescheduleRoute: SessionsSessionIdRescheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
